"""TrendReporter — aggregates CommentData into a weekly trend markdown report."""

from collections import Counter
from datetime import datetime, timezone

from agents.reporting.linker import CommentData


class TrendReporter:
    def build(self, comments: list[CommentData], repo: str) -> str:
        """Return a markdown report string from the collected comment data."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        issues = [c for c in comments if c.kind == "issue"]
        prs = [c for c in comments if c.kind == "pr"]

        lines = [
            f"# AI-DLC Weekly Trend Report — {now}",
            f"\n**Repository**: `{repo}`  ",
            f"**Period**: last 7 days  ",
            f"**Issues triaged**: {len(issues)}  ",
            f"**PRs reviewed**: {len(prs)}\n",
        ]

        lines += self._issue_section(issues)
        lines += self._pr_section(prs)
        lines += self._rules_section(prs)
        lines += ["\n---", "_Generated by the AI-DLC GitHub Agent._"]

        return "\n".join(lines)

    # ------------------------------------------------------------------

    def _issue_section(self, issues: list[CommentData]) -> list[str]:
        if not issues:
            return ["\n## Issue Triage\n_No issues triaged this week._\n"]

        type_counts = Counter(c.issue_type or "unknown" for c in issues)
        sev_counts: Counter = Counter()
        for c in issues:
            sev_counts.update(c.severities)

        lines = ["\n## Issue Triage\n"]
        lines.append("### By Type\n")
        lines.append("| Type | Count |")
        lines.append("|---|---|")
        for t, n in type_counts.most_common():
            lines.append(f"| {t.capitalize()} | {n} |")

        if sev_counts:
            lines.append("\n### By Severity\n")
            lines.append("| Severity | Count |")
            lines.append("|---|---|")
            for emoji, sev in [("🔴", "critical"), ("🟠", "high"), ("🟡", "medium"), ("🟢", "low")]:
                count = sev_counts.get(sev, 0)
                if count:
                    lines.append(f"| {emoji} {sev.capitalize()} | {count} |")

        return lines

    def _pr_section(self, prs: list[CommentData]) -> list[str]:
        if not prs:
            return ["\n## PR Reviews\n_No PRs reviewed this week._\n"]

        total_findings = sum(c.findings_count for c in prs)
        total_fix_prs = sum(c.fix_pr_count for c in prs)
        approved = sum(1 for c in prs if c.findings_count == 0)

        lines = ["\n## PR Reviews\n"]
        lines.append(f"- **PRs reviewed**: {len(prs)}")
        lines.append(f"- **Auto-approved (no findings)**: {approved}")
        lines.append(f"- **Total findings**: {total_findings}")
        if total_findings:
            avg = total_findings / len(prs)
            lines.append(f"- **Average findings per PR**: {avg:.1f}")
        lines.append(f"- **Automated fix PRs opened**: {total_fix_prs}")
        lines.append("")
        return lines

    def _rules_section(self, prs: list[CommentData]) -> list[str]:
        all_rules: Counter = Counter()
        for c in prs:
            all_rules.update(c.rules_violated)

        if not all_rules:
            return []

        lines = ["\n## Most Common Rule Violations\n"]
        lines.append("| Rule | Violations |")
        lines.append("|---|---|")
        for rule, count in all_rules.most_common(10):
            lines.append(f"| `{rule}` | {count} |")
        lines.append("")
        return lines
