"""FixAgent — creates a fix branch, commits the fix, and opens a fix PR."""

import re
from dataclasses import dataclass

from agents.core.github_client import GitHubClient, GitHubPR


@dataclass
class FixPRResult:
    finding: dict
    fix_branch: str
    fix_pr_number: int | None
    success: bool
    error: str | None = None


class FixAgent:
    def __init__(self, github_client: GitHubClient) -> None:
        self.client = github_client

    def run(self, finding: dict, pr: GitHubPR) -> FixPRResult:
        """
        Create a fix branch off pr.head_branch, commit fix_code, open a fix PR.
        Posts a comment on the original PR linking to the fix PR.
        """
        fix_code = finding.get("fix_code")
        file_path = finding.get("file")

        if not fix_code or not file_path:
            return FixPRResult(
                finding=finding,
                fix_branch="",
                fix_pr_number=None,
                success=False,
                error="fix_code or file path missing",
            )

        branch_name = _make_branch_name(finding, pr.number)

        # Create branch off the PR's head branch
        if not self.client.create_branch(branch_name, pr.head_branch):
            return FixPRResult(
                finding=finding, fix_branch=branch_name,
                fix_pr_number=None, success=False,
                error=f"failed to create branch {branch_name}",
            )

        # Commit the fix
        commit_message = _make_commit_message(finding)
        if not self.client.commit_file(branch_name, file_path,
                                       fix_code, commit_message):
            return FixPRResult(
                finding=finding, fix_branch=branch_name,
                fix_pr_number=None, success=False,
                error="failed to commit fix",
            )

        # Open fix PR targeting the original PR's head branch
        pr_title = _make_pr_title(finding, pr.number)
        pr_body = _make_pr_body(finding, pr.number)
        fix_pr_number = self.client.create_pr(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=pr.head_branch,
        )

        if fix_pr_number is None:
            return FixPRResult(
                finding=finding, fix_branch=branch_name,
                fix_pr_number=None, success=False,
                error="failed to open fix PR",
            )

        # Comment on original PR
        self.client.post_comment(
            pr.number,
            f"🔧 Opened fix PR #{fix_pr_number} for: "
            f"{finding.get('message', 'automated fix')}\n"
            f"Please review and merge: #{fix_pr_number}"
        )

        return FixPRResult(
            finding=finding, fix_branch=branch_name,
            fix_pr_number=fix_pr_number, success=True,
        )


def _make_branch_name(finding: dict, pr_number: int) -> str:
    identifier = finding.get("rule_id") or finding.get("_agent", "fix")
    safe_id = re.sub(r"[^a-zA-Z0-9\-]", "-", identifier).lower()
    return f"fix/{safe_id}-pr-{pr_number}"


def _make_commit_message(finding: dict) -> str:
    rule = finding.get("rule_id", "")
    msg = finding.get("message", "automated fix")
    prefix = f"fix({rule}): " if rule else "fix: "
    return prefix + msg[:72]


def _make_pr_title(finding: dict, pr_number: int) -> str:
    rule = finding.get("rule_id", "")
    msg = finding.get("message", "automated fix")[:60]
    prefix = f"fix({rule}): " if rule else "fix: "
    return f"{prefix}{msg} (found in PR #{pr_number})"


def _make_pr_body(finding: dict, pr_number: int) -> str:
    return (
        f"## Automated Fix\n\n"
        f"This PR was automatically generated by the AI-DLC PR Review agent.\n\n"
        f"**Found in**: PR #{pr_number}\n"
        f"**Rule**: {finding.get('rule_id', 'N/A')}\n"
        f"**Severity**: {finding.get('severity', 'unknown')}\n"
        f"**File**: `{finding.get('file', 'unknown')}`\n\n"
        f"**Issue**: {finding.get('message', '')}\n\n"
        f"Please review this fix before merging. Human approval is required.\n\n"
        f"<!-- ai-dlc-fix-pr -->"
    )
